#!/usr/bin/env bash

# Grab all the tags for hugo, order them by semantic versioning
VERSIONS="$(\
    git ls-remote https://github.com/mholt/caddy.git | \
        grep tags | \
        awk '{print $2}' | \
        sed '/{}/d' | \
        sed 's/^refs\/tags\/v//' | \
        sort -V \
)"

for version in $VERSIONS; do
    dl_url="https://github.com/mholt/caddy/releases/download/v${version}/caddy_v${version}_linux_amd64.tar.gz"
    status="$(curl -fsSL -o /dev/null -w "%{http_code}" "$dl_url" 2>/dev/null)"
    # Only support things that follow the latest naming conventions
    if [ "$status" = "200" ]; then
        # Only do it if we get a binary named hugo, why name things like hugo-{kernel}-{uname -m}?
        if curl -fsSL "$dl_url" | tar -tzf - | grep "^caddy$" >/dev/null; then
            echo "$version"
        fi
    fi
done
